/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef ANTLR4_CPP_BAKE_CONFIG_H
#define ANTLR4_CPP_BAKE_CONFIG_H

/* Headers of public dependencies */
/* No dependencies */

/* Headers of private dependencies */
#ifdef ANTLR4_CPP_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if ANTLR4_CPP_IMPL && defined _MSC_VER
#define ANTLR4_CPP_EXPORT __declspec(dllexport)
#elif ANTLR4_CPP_IMPL
#define ANTLR4_CPP_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
#define ANTLR4_CPP_EXPORT __declspec(dllimport)
#else
#define ANTLR4_CPP_EXPORT
#endif

#endif

